### ISSUE TITLE
Memory error when running large amount of files

### ISSUE THREAD

**Issue by eddotman** [iesl/rexa1-metatagger#2]
So I tried running on a large dataset of files (~8k articles), but after ~1.7k articles, the program crashed with the following error:

```
  Dumping heap to java_pid52217.hprof ...
  Heap dump file created [4645038846 bytes in 38.414 secs]
  [error] (run-main-0) java.lang.OutOfMemoryError: Java heap space
  java.lang.OutOfMemoryError: Java heap space
    at java.util.Arrays.copyOf(Arrays.java:2367)
    at java.lang.AbstractStringBuilder.expandCapacity(AbstractStringBuilder.java:130)
    at java.lang.AbstractStringBuilder.ensureCapacityInternal(AbstractStringBuilder.java:114)
    at java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:415)
    at java.lang.StringBuffer.append(StringBuffer.java:237)
    at edu.umass.cs.mallet.base.pipe.tsf.OffsetConjunctions.makeConjunctions(OffsetConjunctions.java:141)
    at edu.umass.cs.mallet.base.pipe.tsf.OffsetConjunctions.makeConjunctions(OffsetConjunctions.java:151)
    at edu.umass.cs.mallet.base.pipe.tsf.OffsetConjunctions.makeConjunctions(OffsetConjunctions.java:151)
    at edu.umass.cs.mallet.base.pipe.tsf.OffsetConjunctions.pipe(OffsetConjunctions.java:106)
    at edu.umass.cs.mallet.base.pipe.SerialPipes.pipe(SerialPipes.java:152)
    at edu.umass.cs.mallet.base.pipe.SerialPipes.pipe(SerialPipes.java:229)
    at edu.umass.cs.mallet.base.types.Instance.<init>(Instance.java:105)
    at edu.umass.cs.mallet.base.fst.Transducer.viterbiPath(Transducer.java:2159)
    at edu.umass.cs.mallet.base.extract.CRFExtractor.extract(CRFExtractor.java:85)
    at org.rexo.pipeline.ReferenceExtractionFilter.doExtraction(ReferenceExtractionFilter.java:175)
    at org.rexo.pipeline.ReferenceExtractionFilter.accept(ReferenceExtractionFilter.java:104)
    at org.rexo.pipeline.components.RxPipeline.execute(RxPipeline.java:92)
    at org.rexo.ui.MetaTag$.main(MetaTag.scala:165)
    at org.rexo.ui.MetaTag.main(MetaTag.scala)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
```

Any suggestions on how to avoid this?

**Comment by adamchandra** [comment]
I'm pretty sure I used to run it on batches of pdfs under 1k or so, so my
first suggestion would be to sidestep the issue and just break up the work
load into smaller sections. You could also set the the java options in the
runcrf script to increase the memory (-xmx 8g or whatever memory you have
available). That might just put off the out of mem error for a bit longer,
though, if there is indeed a memory leak. If the first option isn't
feasible as a stopgap, we will look into plugging the memory hole.

-adam

**Comment by eddotman** [comment]
Gotcha, thanks. I think those approaches should be sufficient for this size of dataset (since I'll only need to split into a couple batches).
